### ISSUE TITLE
Issue following the readme

### ISSUE THREAD

**Issue by jalshorji** [keeps/roda-plugin-template#4]
When I start the container I can open roda but there is no header and I get this error 
org.roda.wui.RodaWUI-0.js:10476 Fri Oct 13 14:20:50 GMT+200 2023 org.roda.wui.client.main.Menu
SEVERE: Error getting Authenticated user
com.google.gwt.user.client.rpc.StatusCodeException: 500  The call failed on the server; see

**Comment by luis100** [comment]
Please check the server logs to see the error that happened on the server.

**Comment by jalshorji** [comment]
This is the error in the tomcat server. 

`16-Oct-2023 06:24:31.098 SEVERE [http-nio-8080-exec-3] org.apache.catalina.core.ApplicationContext.log Exception while dispatching incoming RPC call
        com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.roda.core.data.v2.user.User org.roda.wui.client.common.UserLoginService.getAuthenticatedUser() throws org.roda.core.data.exceptions.RODAException' threw an unexpected exception: java.lang.NullPointerException: Cannot invoke "org.roda.core.model.utils.LdapUtility.getUser(String)" because "org.roda.core.model.utils.UserUtility.ldapUtility" is null
                at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
                at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
                at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:528)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.roda.wui.filter.OnOffFilter.doFilter(OnOffFilter.java:75)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:607)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:389)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
                at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Unknown Source)
        Caused by: java.lang.NullPointerException: Cannot invoke "org.roda.core.model.utils.LdapUtility.getUser(String)" because "org.roda.core.model.utils.UserUtility.ldapUtility" is null
                at org.roda.core.model.utils.UserUtility.getGuest(UserUtility.java:256)
                at org.roda.core.model.utils.UserUtility.getUser(UserUtility.java:87)
                at org.roda.core.model.utils.UserUtility.getUser(UserUtility.java:99)
                at org.roda.wui.server.common.UserLoginServiceImpl.getAuthenticatedUser(UserLoginServiceImpl.java:43)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.base/java.lang.reflect.Method.invoke(Unknown Source)
                at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
                ... 37 more`

Why does it try to use ldap?

**Comment by luis100** [comment]
It is an internal LDAP server to keep the internal users.
Seems to me an initialization issue, due to an previous error, can you check any previous errors?

**Comment by 006627** [comment]
Hello, this project has been update to use RODA 5, which depends on a set of additional services to work correctly, we will update  the README instructions as soon as possible.
